POST http://localhost:3000/addNotes
Content-Type: application/json

{
    "content": "Learn Backend Technologies"
}

###

GET http://localhost:3000/notes

###

DELETE http://localhost:3000/notes/34

###